language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - cd Week4/Tests
    - python -m unittest discover . coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
  